### ISSUE TITLE
Options not Displaying

### ISSUE THREAD

**Issue by AkshantLanjewar** [newcat/baklavajs#142] opened 2021-06-10 00:58 UTC
I was following the https://codesandbox.io/s/jyc6f example and tried to replicate it on my machine. But when I run the code, there is no options showing up on the nodes?

![options](https://user-images.githubusercontent.com/52946571/121448245-13b10d80-c94c-11eb-90b7-547c229f42d5.png)

`import Hint from './Hint.vue'

    import { Editor } from "@baklavajs/core";
    import { ViewPlugin } from "@baklavajs/plugin-renderer-vue";
    import { OptionPlugin } from "@baklavajs/plugin-options-vue";
    import { Engine } from "@baklavajs/plugin-engine";

    //nodes
    import { ArithmaticNode } from './nodes/ArithmaticNode'
    import { DisplayNode } from './nodes/DisplayNode'

    export default {
        components: { Hint },
        data() {
            return {
                editor: new Editor(),
                viewPlugin: new ViewPlugin(),
                engine: new Engine(true)
            }
        },

        created() {
            this.editor.use(this.viewPlugin)
            this.editor.use(new OptionPlugin())
            this.editor.use(this.engine)
            this.viewPlugin.enableMinimap = true

            //registering the nodes
            this.editor.registerNodeType("ArithmaticNode", ArithmaticNode)
            this.editor.registerNodeType("DisplayNode", DisplayNode)

            //add node
            const node1 = this.addNodeWithCoordinates(ArithmaticNode, 0, 0)
            const node2 = this.addNodeWithCoordinates(DisplayNode, 280, 20)

            this.editor.addConnection(
                node1.getInterface("Result"),
                node2.getInterface("Value")
            )

            this.calculate()
        },

        methods: {
            addNodeWithCoordinates(nodeType, x, y) {
                const n = new nodeType()

                this.editor.addNode(n)
                n.position.x = x
                n.position.y = y
                return n
            }
        }
    }`

` import { NodeBuilder } from '@baklavajs/core'

export const DisplayNode = new NodeBuilder("DisplayNode")
    .setName("Display")
    .addInputInterface("Value")
    .addOption("ValueText", "TextOption")
    .onCalculate(n => {
        let value = n.getInterface("Value").value
        if (typeof value === "number")
            value = value.toFixed(3)
        n.setOptionValue("ValueText", value)
    })
    .build() `

**Comment by AkshantLanjewar** [comment] 2021-06-10 00:58
`
import { Node } from '@baklavajs/core'

export class ArithmaticNode extends Node {
    constructor() {
        super()

        this.type = "ArithmaticNode"
        this.name = "Arithmatic"

        this.addInputInterface("Number 1", "NumberOption", 0)
        this.addInputInterface("Number 2", "NumberOption", 0)
        
        this.addOption("Operation", "Operation", {
            selected: "Add",
            items: ["Add", "Subtract", "Multiply", "Divide"]
        })

        this.addOutputInterface("Result")
    }

    calculate() {
        const n1 = this.getInterface("Number 1").value
        const n2 = this.getInterface("Number 2").value
        const operation = this.getOptionValue("Operation").selected

        let result
        if (operation === "Add")
            result = n1 + n2
        if (operation === "Subtract")
            result = n1 - n2
        if (operation === "Multiply")
            result = n1 * n2
        if (operation === "Divide")
            result = n1 / n2

        this.getInterface("Result").value = result
    }
}
`

**Comment by newcat** [comment] 2021-06-13 18:19
Can you provide a repo that I can clone so I can also see the configuration files?

**Comment by ashleysommer** [comment] 2021-06-29 23:45
I ran across the same problem yesterday.
@AkshantLanjewar You need to use `InputOption`, not `TextOption`. `InputOption` gives you a text box for `ValueText` input.

Its not clear, but it seems like `TextOption` is used for another purpose.

**Comment by newcat** [comment] 2021-06-30 20:23
@ashleysommer I think in this case `TextOption` is the correct option to use, since he just wants to display the result of the calculation, like in the CodeSandbox linked above.

But I do agree that the option names are confusing. I am going to change them in Baklava v2.

**Comment by ashleysommer** [comment] 2021-06-30 21:56
Ah, yes, I re-read the code, and you're right.

**Comment by newcat** [comment] 2021-08-20 23:13
Closing this for now. If the issue persists, please reopen and provide more information to help me reproduce the issue.

**Closed** 2021-08-20 23:12 UTC
