### ISSUE TITLE
Vuetify kills the background grid and adds a shadow

### ISSUE THREAD

**Issue by code-is-art** [newcat/baklavajs#119] opened 2021-01-25 21:25 UTC
Currently adding Vuetify to the project kills the background grid and adds a shadow on the right. There must be some css naming conflict. You can reproduce following the instructions on [this issue](https://github.com/newcat/baklavajs/issues/118) and after
```console
vue create baklava-test
cd baklava-test
```
add
```console
vue add vuetify
```
continue with the steps outlined. If there is an easy way around this please advice until a solution is found.

**Comment by code-is-art** [comment] 2021-01-25 21:49
it has to do with the background-repeat css property but I haven't figured out how to fix it yet.
![background-repeat](https://user-images.githubusercontent.com/50637029/105770431-30b0eb00-5f2d-11eb-93a1-96898357b990.png)

**Comment by code-is-art** [comment] 2021-01-25 21:56
in node-editor.scss and added it to styles.css
![Screen Shot 2021-01-25 at 4 55 02 PM](https://user-images.githubusercontent.com/50637029/105771234-3a871e00-5f2e-11eb-92fb-7a76e30ffb2a.png)

**Comment by newcat** [comment] 2021-01-31 02:21
Regarding the background grid: I can't reproduce this, neither with the steps described in the issue, nor in [this sandbox](https://codesandbox.io/s/baklava-vuetify-6f51p?file=/src/main.js).

The shadow is actually from Baklava's sidebar itself. I'll fix this in the next version.

**Comment by LukasLoeffler** [comment] 2021-03-01 14:01
For me upgrading BakkavaJS to v1.8.3 did the trick.
I was on v1.7.5 before and the grid was not visible.
This may be a reason newcat could not reproduce the issue.

**Comment by newcat** [comment] 2021-03-07 16:37
Good to know! Indeed, the handling of the background changed in v1.8.0. I fixed the shadow issue in v1.8.3, so I'll close this issue now. Feel free to reopen if you still have issues.

**Closed by newcat** 2021-03-07 16:37 UTC
